site_name: Jupyblog
site_url: https://example.com/
theme:
  name: material
nav:
  - Home: index.md
  - Example: post.md
  - Rendered: output/docs.md
# https://github.com/squidfunk/mkdocs-material/issues/156#issuecomment-691507925
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences